apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/borkar-shubham/argocd-apps
    targetRevision: HEAD
    path: tomcat
  destination:
    server: https://kubernetes.default.svc
    namespace: tomcat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
